apps/front/forms.py
from flask import request
from wtforms.fields import StringField, IntegerField, FileField
from wtforms import Form, ValidationError
from wtforms.validators import Email, Length, EqualTo, InputRequired
from flask_wtf.file import FileAllowed, FileSize
from models.auth import UserModel
from exts import cache


class BaseForm(Form):
    @property
    def messages(self):
        message_list = []
        if self.errors:
            for errors in self.errors.values():
                message_list.extend(errors)
        return message_list


class RegisterForm(BaseForm):
    # pip install email_validator
    email = StringField(validators=[Email(message="請輸入正確的Email")])
    email_captcha = StringField(validators=[Length(6, 6, message="請輸入正確的email驗證碼")])
    username = StringField(validators=[Length(3, 20, message="請輸入3-20個字長的用戶名")])
    password = StringField(validators=[Length(6, 20, message="請輸入6-20位密碼")])
    repeat_password = StringField(validators=[EqualTo("password", message="兩次輸入密碼不一致")])
    graph_captcha = StringField(validators=[Length(4, 4, message="請輸入正確的圖形驗證碼")])

    def validate_email(self, field):
        email = field.data
        user = UserModel.query.filter_by(email=email).first()
        if user:
            raise ValidationError(message="Email不能重複註冊")

    def validate_email_captcha(self, field):
        email_captcha = field.data
        email = self.email.data
        # 從緩存取出驗證碼
        cache_captcha = cache.get(email)
        if not cache_captcha or email_captcha != cache_captcha:
            raise ValidationError(message="Email驗證碼錯誤")

    def validate_graph_captcha(self, field):
        key = request.cookies.get("_graph_captcha_key")
        # 從緩存取出驗證碼
        cache_captcha = cache.get(key)
        graph_captcha = field.data
        # 全部轉成小寫再比對
        if not cache_captcha or cache_captcha.lower() != graph_captcha.lower():
            raise ValidationError(message="圖形驗證碼錯誤")


class LoginForm(BaseForm):
    email = StringField(validators=[Email(message="請輸入正確的Email")])
    password = StringField(validators=[Length(6, 20, message="請輸入正確的密碼")])
    remember = IntegerField()


class UploadImageForm(BaseForm):
    image = FileField(validators=[FileAllowed(['jpg', 'jpeg', 'png'], message="圖片格式不符合規定"), FileSize(max_size=1024*1024*5, message="圖片最大不能超過5M")])


class EditProfileForm(BaseForm):
    signature = StringField(validators=[Length(max=50, message="個性簽名最多50字")])


class PublicPostForm(BaseForm):
    title = StringField(validators=[Length(max=200, message="討論標題最多200字")])
    content = StringField(validators=[InputRequired(message="請輸入內容")])
    board_id = IntegerField(validators=[InputRequired(message="請選擇討論分類")])


class PublicCommentForm(BaseForm):
    content = StringField(validators=[InputRequired(message="請輸入內容")])
    post_id = IntegerField(validators=[InputRequired(message="請選擇討論文章")])

apps/front/__init__.py
from .views import bp as front_bp

apps/front/views.py
from flask import Blueprint, request, render_template, current_app, make_response, session, redirect, g
import string
import random
from hashlib import md5
from io import BytesIO
import time
from flask_avatars import Identicon
import os
from flask_paginate import get_page_parameter, Pagination
from sqlalchemy.sql import func

from exts import db, cache
from utils import restful
from utils.captcha import Captcha
from .forms import RegisterForm, LoginForm, UploadImageForm, EditProfileForm, PublicPostForm, PublicCommentForm
from models.auth import UserModel
from models.post import BoardModel, PostModel, CommentModel, BannerModel
from .decorators import login_required

bp = Blueprint("front", __name__, url_prefix="/")

# 請求過程:before_request => blueprint函數（返回模板） => context_processor => 將context_processor返回的變量也添加到模板中


# 鉤子函數：before_request，在調用其他blueprint內函數前執行
@bp.before_request
def front_before_request():
    if 'user_id' in session:
        user_id = session.get("user_id")
        user = UserModel.query.get(user_id)
        # setattr(object, name, values):給object的屬性賦值，若屬性不存在，先創建再賦值
        setattr(g, "user", user)


# 上下文處理器
@bp.context_processor
def front_context_processor():
    # hasattr(object, name):判斷object裡是否有name屬性或name方法，返回bool值
    if hasattr(g, "user"):
        return {"user": g.user}
    else:
        return {}


@bp.route("/")
def index():
    sort = request.args.get("st", type=int, default=1)
    board_id = request.args.get("bd", type=int, default=None)
    boards = BoardModel.query.order_by(BoardModel.priority.desc()).all()
    post_query = None
    if sort == 1:
        post_query = PostModel.query.order_by(PostModel.create_time.desc())
    else:
        # 根據討論量進行排序
        post_query = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(
            func.count(CommentModel.id).desc(), PostModel.create_time.desc())

    page = request.args.get(get_page_parameter(), type=int, default=1)
    # 1：0-9
    # 2：10-19
    start = (page - 1) * current_app.config['PER_PAGE_COUNT']
    end = start + current_app.config['PER_PAGE_COUNT']

    if board_id:
        # "mapped class CommentModel->comment" has no property "board_id"
        # CommentModel中尋找board_id，然后進行filter
        # post_query = post_query.filter_by(board_id=board_id)
        post_query = post_query.filter(PostModel.board_id == board_id)
    total = post_query.count()
    posts = post_query.slice(start, end)
    pagination = Pagination(bs_version=3, page=page, total=total, prev_label="上一頁")

    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()
    context = {
        "boards": boards,
        "posts": posts,
        "pagination": pagination,
        "st": sort,
        "bd": board_id,
        "banners": banners
    }
    return render_template("front/index.html", **context)


@bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("front/login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            print(request.form)
            print(type(request.form))
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                return restful.params_error("Email或密碼錯誤")
            if not user.check_password(password):
                return restful.params_error("Email或密碼錯誤")
            if not user.is_active:
                return restful.params_error("此用戶不可登入")
            session['user_id'] = user.id
            if remember == 1:
                # 默認session過期時間，只要瀏覽器關閉就會過期
                session.permanent = True
            return restful.ok()
        else:
            return restful.params_error(message=form.messages[0])


@bp.route("/logout")
def logout():
    session.clear()
    return redirect("/")


@bp.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("front/register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            identicon = Identicon()
            filenames = identicon.generate(text=md5(email.encode("utf-8")).hexdigest())
            avatar = filenames[2]
            user = UserModel(email=email, username=username, password=password, avatar=avatar)
            db.session.add(user)
            db.session.commit()
            return restful.ok()
        else:
            # form.errors中存放了所有的錯誤訊息
            # {'graph_captcha': ['請輸入正確的圖形驗證碼！', '圖形驗證碼錯誤！']}
            message = form.messages[0]
            return restful.params_error(message=message)


@bp.get("/email/captcha")
def email_captcha():
    email = request.args.get("email")
    if not email:
        return restful.params_error(message="請先輸入Email")
    # 隨機6位數
    source = list(string.digits)
    captcha = "".join(random.sample(source, 6))
    subject = "【齊助浪寶】註冊驗證碼"
    body = "【齊助浪寶】您的註冊驗證碼：%s" % captcha
    current_app.celery.send_task("send_mail", (email, subject, body))
    cache.set(email, captcha)
    print(cache.get(email))
    return restful.ok(message="Email發送成功")


@bp.route("/graph/captcha")
def graph_captcha():
    captcha, image = Captcha.gene_graph_captcha()
    # 緩存驗證碼
    # key, value
    # bytes
    key = md5((captcha+str(time.time())).encode('utf-8')).hexdigest()
    cache.set(key, captcha)
    print(cache.set(key, captcha))
    out = BytesIO()
    image.save(out, "png")
    # 把out的文件指针指向一開始的位置
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = "image/png"
    # 把key設置到cookie
    resp.set_cookie("_graph_captcha_key", key, max_age=3600)
    return resp


@bp.route("/setting")
@login_required
def setting():
    email_hash = md5(g.user.email.encode("utf-8")).hexdigest()
    return render_template("front/setting.html", email_hash=email_hash)


@bp.post("/avatar/upload")
@login_required
def upload_avatar():
    form = UploadImageForm(request.files)
    if form.validate():
        image = form.image.data
        # 不使用用戶自己傳上來的文件名，避免惡意攻擊
        filename = image.filename
        # xxx.png,xx.jpeg
        _, ext = os.path.splitext(filename)
        filename = md5((g.user.email + str(time.time())).encode("utf-8")).hexdigest() + ext
        image_path = os.path.join(current_app.config['AVATARS_SAVE_PATH'], filename)
        image.save(image_path)
        g.user.avatar = filename
        db.session.commit()
        return restful.ok(data={"avatar": filename})
    else:
        message = form.messages[0]
        return restful.params_error(message=message)


@bp.post("/profile/edit")
@login_required
def edit_profile():
    form = EditProfileForm(request.form)
    if form.validate():
        signature = form.signature.data
        g.user.signature = signature
        db.session.commit()
        return restful.ok()
    else:
        return restful.params_error(message=form.messages[0])


@bp.route("/post/public", methods=['GET', 'POST'])
@login_required
def public_post():
    if request.method == 'GET':
        boards = BoardModel.query.order_by(BoardModel.priority.desc()).all()
        return render_template("front/public_post.html", boards=boards)
    else:
        form = PublicPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            try:
                # get方法：接收id，如果id存在就會返回
                # 如果没有找到id就會報錯
                board = BoardModel.query.get(board_id)
            except:
                return restful.params_error(message="討論分類不存在！")
            post_model = PostModel(title=title, content=content, board=board, author=g.user)
            db.session.add(post_model)
            db.session.commit()
            return restful.ok(data={"id": post_model.id})
        else:
            return restful.params_error(message=form.messages[0])


@bp.post("/post/image/upload")
@login_required
def upload_post_image():
    form = UploadImageForm(request.files)
    if form.validate():
        image = form.image.data
        # 不要使用用户上传上来的文件名，否则容易被黑客攻击
        filename = image.filename
        # xxx.png,xx.jpeg
        _, ext = os.path.splitext(filename)
        filename = md5((g.user.email + str(time.time())).encode("utf-8")).hexdigest() + ext
        image_path = os.path.join(current_app.config['POST_IMAGE_SAVE_PATH'], filename)
        image.save(image_path)
        # {"data","code", "message"}
        return jsonify({"errno": 0, "data": [{
            "url": url_for("media.get_post_image", filename=filename),
            "alt": filename,
            "href": ""
        }]})
    else:
        message = form.messages[0]
        return restful.params_error(message=message)


@bp.get("/post/detail/<post_id>")
def post_detail(post_id):
    post_model = PostModel.query.get(post_id)
    comment_count = CommentModel.query.filter_by(post_id=post_id).count()
    context = {
        "comment_count": comment_count,
        "post": post_model
    }
    return render_template("front/post_detail.html", **context)


@bp.post("/comment")
@login_required
def public_comment():
    form = PublicCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        try:
            post_model = PostModel.query.get(post_id)
        except:
            return restful.params_error(message="文章不存在！")
        comment = CommentModel(content=content, post_id=post_id, author_id=g.user.id)
        db.session.add(comment)
        db.session.commit()
        return restful.ok()
    else:
        message = form.messages[0]
        return restful.params_error(message=message)

apps/media/views.py
from flask import Blueprint, send_from_directory, current_app

bp = Blueprint("media", __name__, url_prefix="/media")

# /media/avatar/abc.jpg
# 部署的时候，在nginx中配置一个/meida前缀的url
# 访问/media的时候，我们指定让他从media文件夹下寻找文件


@bp.route("/avatar/<filename>")
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


# www.zlkt.net/media/post/abc.png
@bp.route("/post/<filename>")
def get_post_image(filename):
    return send_from_directory(current_app.config['POST_IMAGE_SAVE_PATH'], filename)


@bp.route("/banner/<filename>")
def get_banner_image(filename):
    return send_from_directory(current_app.config['BANNER_IMAGE_SAVE_PATH'], filename)

templates/front/base.html
<html>
<head>
    <meta charset="utf-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='front/js/petajax.js') }}"></script>
    <script src="{{ url_for('static', filename='front/js/param.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='front/css/front_base.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
</head>

<body style="background-color:#FFFFFF">
    <nav class="navbar navbar-default" style="background-color:#D0DCC6" >
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/" style="font-weight: bold;">齊助浪寶討論專區</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >
                <ul class="nav navbar-nav" >
                    <li class="active"><a href="/" style="background-color:#D0DCC6">首頁<span class="sr-only">(current)</span></a></li>
                </ul>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="請輸入關鍵字" style="border-radius:10px;">
                    </div>
                    <button type="submit" class="btn btn-default" style="background-color:#FCD52E;border-radius:20px;"><font color="#5B6056">Search</font></button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if user %}
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="background-color:#D0DCC6">
                              {{ user.username }}
                              <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" style="border-radius:20px;">
                              <li><a href="{{ url_for('front.setting') }}">管理後台</a></li>
                              <li><a href="{{ url_for('front.setting') }}">用戶後台</a></li>
                              <li><a href="{{ url_for('front.logout') }}">登出</a></li>
                          </ul>
                      </li>
                    {% else %}
                      <li><a href="{{ url_for('front.login') }}">登入</a></li>
                      <li><a href="{{ url_for('front.register') }}">註冊</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="main-container">
        {% block body %}{% endblock %}
    </div>
</body>

</html>

templates/front/index.html
{% extends "front/base.html" %}

{% block title %}
  齊助浪寶討論專區
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static',filename='front/css/index.css')}}">
{% endblock %}

{% block body %}
<div class="lg-container">
            <div class="post-group" style="border-radius:20px;">
              <ul class="post-group-head">
                {% if st == 1 %}
                  <li class="active" style="background-color:#D0DCC6; border-radius:10px;text-align:center;">
                {% else %}
                  <li>
                {% endif %}
                <a href="{{ url_for("front.index", st=1, bd=bd) }}"><font color="#5B6056">最新</font></a>
                  </li>

                {% if st == 2 %}
                  <li class="active" style="background-color:#D0DCC6; border-radius:10px;text-align:center;">
                {% else %}
                  <li>
                {% endif %}
                <a href="{{ url_for('front.index', st=2, bd=bd) }}"><font color="#5B6056">最多討論</font></a>
                </li>
              </ul>
              <ul class="post-list-group">
                {% for post in posts %}
                  <li>
                    <div class="author-avatar-group">
                      <img src="{{ url_for('media.get_avatar', filename=post.author.avatar) }}" alt="">
                    </div>
                    <div class="post-info-group">
                      <p class="post-title">
                        <a href="{{ url_for('front.post_detail', post_id=post.id) }}">{{ post.title }}</a>
                      </p>
                      <p class="post-info">
                        <span>作者：{{ post.author.username }}</span>
                        <span>發表時間：{{ post.create_time }}</span>
                        <span>評論:{{ post.comments|length }}</span>
                      </p>
                    </div>
                  </li>
                {% endfor %}
              </ul>
              <div style="text-align: center;">
                {{ pagination.links }}
              </div>
            </div>
          </div>
<div class="sm-container">
          <div style="padding-bottom:10px;">
            <a href="{{ url_for('front.public_post') }}" class="btn btn-warning btn-block" style="background-color:#FCD52E; border-radius:20px; border-color:#FCD52E;"><font color="#5B6056">發布討論</font></a>
          </div>
          <div class="list-group">
              {% if bd %}
                <a href="/" class="list-group-item" style="background-color:#D0DCC6; border-radius:10px;text-align:center;">所有專區</a>
              {% else %}
            <a href="/" class="list-group-item active" style="background-color:#D0DCC6; border-radius:10px; text-align:center; border-color:#D0DCC6;"><font color="#5B6056">所有專區</font></a>
              {% endif %}

              {% for board in boards %}
                {% if bd == board.id %}
                  <a href="{{ url_for('front.index', bd=board.id, page=1) }}" class="list-group-item active" style="border-radius:10px;background-color:#F1EDE2;border-color:#D0DCC6;color=#5B6056;">
                {% else %}
                  <a href="{{ url_for('front.index', bd=board.id, page=1) }}" class="list-group-item" style="border-radius:10px;text-align:center;">
                {% endif %}
                    <font color="#5B6056">{{ board.name }}</font>
                </a>
              {% endfor %}
          </div>
        </div>
{% endblock %}

templates/front/login.html
{% extends "front/base.html" %}

{% block title %}
  登入 - 齊助浪寶討論專區
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static', filename='front/css/signbase.css') }}">
  <script src="{{ url_for('static', filename='front/js/login.js') }}"></script>
{% endblock %}


{% block body %}
  <div class="outer-box" style="background-color:#F1EDE2; box-shadow:3px 12px 12px #cccccc;">
    <div class="logo-box" >
      <a href="/">
        <img src="{{ url_for('static', filename='front/images/logo.png') }}" alt="">
      </a>
    </div>
    <br>
    <h2 class="page-title">
      <font color="#5B6056">登入 - 齊助浪寶</font>
    </h2>
    <div class="sign-box">
      <div class="form-group">
        <input type="text" class="form-control" name="email" placeholder="Email" style="border-radius:10px;">
      </div>
      <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="密碼" style="border-radius:10px;">
      </div>
      <div class="checkbox">
        <label>
          <input type="checkbox" name="remember" value="1">remember me
        </label>
      </div>
      <div class="form-group">
        <button class="btn btn-warning btn-block" id="submit-btn" style="background-color:#FCD52E; border-radius:20px;"><font color="#5B6056">登入</font></button>
      </div>
      <div class="form-group">
        <a href="{{ url_for('front.register') }}" class="signup-link" style=" display: flex;">立即註冊</a>
        <br>
      </div>
    </div>
  </div>
{% endblock %}

templates/front/post_detail.html
{% extends "front/base.html" %}

{% block title %}
齊助浪寶-{{ post.title }}
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static', filename='lib/highlight/styles/github-dark.min.css') }}">
  <script src="{{ url_for('static', filename='lib/highlight/highlight.min.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='front/css/post_detail.css') }}">
  <script src="{{ url_for('static', filename='front/js/post_detail.js') }}"></script>
{% endblock %}

{% block body %}
<div class="post-container" style=" border-radius:20px;">
      <h2>{{ post.title }}</h2>
      <p class="post-info-group">
        <span>發布時間：{{ post.create_time }}</span>
        <span>作者：{{ post.author.username }}</span>
        <span>討論分類：{{ post.board.name }}</span>
        <span>討論數：{{ comment_count }}</span>
      </p>
      <div class="post-content">
        {{ post.content|safe }}
      </div>
    </div>
<div class="comment-group" style=" border-radius:20px;">
  <h3><font color="#5B6056">討論</font></h3>
  <ul class="comment-list-group">
    {% for comment in post.comments %}
    <li>
      <div class="avatar-group">
        <img src="{{ url_for('media.get_avatar', filename=comment.author.avatar) }}" alt="">
      </div>
      <div class="comment-content">
        <p class="author-info">
          <span>{{ comment.author.username }}</span>
          <span>{{ comment.create_time }}</span>
        </p>
        <p class="comment-txt">
          {{ comment.content }}
        </p>
      </div>
    </li>
    {% endfor %}
  </ul>
</div>
<div class="add-comment-group" style=" border-radius:20px;">
  <h3><font color="#5B6056">參與討論</font></h3>
  <textarea name="comment" id="comment-textarea" style="width: 100%; resize:vertical;border-radius:20px;"></textarea>
  <div class="comment-btn-group">
    <button class="btn btn-default" id="comment-btn" data-post-id="{{ post.id }}" data-user-id="{{ user.id if user else '' }}" style="background-color:#FCD52E; border-radius:20px;">參與討論</button>
  </div>
</div>
{% endblock %}

templates/front/public_post.html
{% extends "front/base.html" %}

{% block title %}
齊助浪寶-發布討論
{% endblock %}

{% block head %}
  <script src="{{ url_for('static', filename='lib/wangEditor/wangEditor.min.js') }}"></script>
  <script src="{{ url_for('static', filename='front/js/public_post.js') }}"></script>
{% endblock %}

{% block body %}
  <h1 style="text-align: center; padding: 20px;color:#5B6056;">發布討論</h1>
    <form action="" method="post">
      <div class="form-group">
        <div class="input-group">
          <span class="input-group-addon" >標題</span>
          <input type="text" class="form-control" name="title" >
        </div>
      </div>
      <div class="form-group">
        <div class="input-group" >
          <span class="input-group-addon" >專區分類</span>
          <select name="board_id" class="form-control" ">
            {% for board in boards %}
              <option value="{{ board.id }}" >{{ board.name }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="form-group" >
        <div id="editor" style="border-radius:10px;"></div>
      </div>
      <div class="form-group">
        <button class="btn btn-default" id="submit-btn" style="background-color:#FCD52E; border-radius:20px;color:#5B6056">發布討論</button>
      </div>
    </form>
{% endblock %}

templates/front/register.html
{% extends "front/base.html" %}

{% block title %}
  註冊-齊助浪寶
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static', filename='front/css/signbase.css') }}">
  <script src="{{ url_for('static', filename='front/js/register.js') }}"></script>
{% endblock %}


{% block body %}
  <div class="outer-box" style="background-color:#F1EDE2;box-shadow:3px 3px 12px #cccccc;">
            <div class="logo-box" style="width: 130px height:100px;">
                <a href="/">
                    <img src="{{ url_for('static', filename='front/images/logo.png') }}" alt="" >
                </a>
            </div>
      <br>
            <h2 class="page-title">
                <font color="#5B6056">註冊-齊助浪寶</font>
            </h2>
            <div class="sign-box">
                <div class="form-group">
                    <div class="input-group">
                        <input type="email" class="form-control" name="email" placeholder="Email" style="border-radius:10px;">
                        <span class="input-group-btn">
                            <button id="email-captcha-btn" class="btn btn-default" style="background-color:#FCD52E;border-radius:10px;margin-left :3px;"><font color="#5B6056">發送Email驗證碼</font></button>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="email-captcha" placeholder="Email驗證碼" style="border-radius:10px;">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="用户名" style="border-radius:10px;">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="密碼" style="border-radius:10px;">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="repeat-password" placeholder="確認密碼" style="border-radius:10px;">
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control" name="graph-captcha" placeholder="圖形驗證碼" style="border-radius:10px;">
                        <span class="input-group-addon captcha-addon" style="border-radius:15px;">
                            <img id="captcha-img" class="captcha-img" src="{{url_for('front.graph_captcha')}}" alt="" style="border-radius:10px;margin-left :3px;">
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-warning btn-block" style="background-color:#FCD52E;border-radius:20px;" id="submit-btn"><font color="#5B6056">註冊</font></button>
                    <br>
                </div>
            </div>
        </div>
{% endblock %}

templates/front/setting.html
{% extends "front/base.html" %}

{% block title %}
用戶後台
{% endblock %}

{% block head %}
  <script src="{{ url_for('static', filename='front/js/setting.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='front/css/index.css') }}">
  <style>
    body{
      background-color: #ffffff;

    }
    .setting-group {
      width: 800px;
      color:#5B6056;
      background-color: #F1EDE2;
      margin: 0 auto;
      padding: 50px;
      border-radius:20px;
      box-shadow:3px 12px 12px #cccccc;
      line-height:30px;
    }
    #avatar-img{
      width: 140px;
      height: 140px;
    }
  </style>
{% endblock %}


{% block body %}
<div class="setting-group">
      <h1>{{ user.username }}用戶後台</h1>
      <div style="height: 20px;"></div>
      <form>
          <div >
              <font color="#5B6056">Email：{{ user.email }}</font>
          </div>
        <div class="form-group">
          <label>頭像：</label>
          <div class="input-group">
            <img src="{{ url_for('media.get_avatar', filename=user.avatar) }}" alt="..." class="img-circle" id="avatar-img">
            <input type="file" id="avatar-input" accept="image/jpeg, image/png"  >
          </div>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">個性簽名：</label>
          <input type="text" class="form-control" id="signagure-input" value="{{ user.signature or "" }}" style="border-radius:10px;">
        </div>
          <button type="submit" id="submit-btn" class="btn btn-default" style="background-color:#FCD52E; border-radius:20px;"><font color="#5B6056">儲存</font></button>
      </form>
    </div>
{% endblock %}